import { useEffect, useState } from "react";
import { toast } from "sonner";
import api, { fmtErr } from "../api";
import { DataTable, PageHead, fmtNum } from "../components";

export default function Consumption() {
  const [rows, setRows] = useState(null);
  useEffect(() => {
    api.get("/consumption").then((r) => setRows(r.data)).catch((e) => toast.error(fmtErr(e)));
  }, []);
  return (
    <div data-testid="consumption-page">
      <PageHead title="Consumption Log" sub="Every expected-consumption calculation generated by a production batch — today" testId="consumption-head" />
      {rows === null ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : (
        <DataTable
          testId="consumption-table"
          cols={["Batch", "Dish", "Ingredient", "Formula", "Expected Qty"]}
          rows={rows.map((c) => [
            <span className="font-mono text-brand-terra">{c.batch_no}</span>,
            c.dish_name,
            c.ingredient_name,
            <span className="font-mono text-muted-foreground">{c.formula}</span>,
            <span className="font-mono">{fmtNum(c.qty)} {c.unit}</span>,
          ])}
        />
      )}
    </div>
  );
}
